name: Green
on:
  repository_dispatch:
    types: [Green]
  workflow_dispatch:
jobs:
   Green:
    name: Green
    runs-on: ubuntu-latest
    steps:
      - name: Green
        uses: actions/checkout@v3
      - name: 'Green'
        run: |
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --local user.name "${GITHUB_ACTOR}"
      - name: Green
        run: chmod +x ./Green.sh && ./Green.sh
